$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code:
  local_path: src
command: >-
  python train.py
environment: azureml:XGBoost-Env:1
compute: azureml:aml-labs-01
display_name: train-model
experiment_name: mlops-churn

